# Generated by Django 4.2.14 on 2024-07-16 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fecha_creacion',
            new_name='fecha_ingreso',
        ),
    ]
