# Generated by Django 4.2.14 on 2024-07-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_fecha_creacion_product_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
