# Generated by Django 4.2.14 on 2024-07-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_descripcion_product_paginas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
