# Generated by Django 4.2.14 on 2024-07-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.TextField(),
        ),
    ]
