# Generated by Django 4.2.14 on 2024-07-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='autor',
            field=models.TextField(),
        ),
    ]
